name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: swift test
        run: swift test
  linux:
    name: Test on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: swift test
        run: swift test
